spring: 
  profiles: 
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-dept-client
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
     url: jdbc:mysql://localhost:3306/springcloud03?characterEncoding=utf8&serverTimezone=UTC&useSSL=false   # 数据库名称
     username: root
     password: 123456
     dbcp2:
       min-idle: 5                                           # 数据库连接池的最小维持连接数
       initial-size: 5                                       # 初始化连接数
       max-total: 5                                          # 最大连接数
       max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/c        # mybatis配置文件所在路径
  type-aliases-package: com.nico.springcloud.entities     # 所有Entity别名类所在包
  mapper-locations: classpath:mapper/*Mapper.xml    # mapper映射文件
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    instance:
      instance-id: dept-8001.com
      prefer-ip-address: true
info:
  app.name: nico-microservicecloud-springcloudconfig01
  company.name: www.nico.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application: 
    name: microservicecloud-config-dept-client
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
     url: jdbc:mysql://localhost:3306/springcloud02?characterEncoding=utf8&serverTimezone=UTC&useSSL=false   # 数据库名称
     username: root
     password: 123456
     dbcp2:
       min-idle: 5                                           # 数据库连接池的最小维持连接数
       initial-size: 5                                       # 初始化连接数
       max-total: 5                                          # 最大连接数
       max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml        # mybatis配置文件所在路径
  type-aliases-package: com.nico.springcloud.entities     # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/*Mapper.xml                       # mapper映射文件
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    instance:
      instance-id: dept-8001.com
      prefer-ip-address: true

info:
  app.name: nico-microservicecloud-springcloudconfig01
  company.name: www.nico.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
